#define IDENTIFIER
#define CONSTANT
#define START
#define FINISH
#define IF
#define ELSE
#define ENDIF
#define FOR
#define FROM
#define TO
#define DO
#define ENDFOR
#define WHILE
#define ENDWHILE
#define GET
#define PRINT
#define INT
#define CONST
#define STRING
#define VECTOR
#define BOOL
#define CHAR
#define REAL
#define SQRT
#define COLON
#define SEMI_COLON
#define COMA
#define DOT
#define LEFT_ROUND_PARENTHESIS
#define RIGHT_ROUND_PARENTHESIS
#define LEFT_SQUARE_PARENTHESIS
#define RIGHT_SQUARE_PARENTHESIS
#define LEFT_BRACKET
#define RIGHT_BRACKET
#define PLUS
#define MINUS
#define MULTIPLY
#define DIVISION
#define LESS_THAN
#define GREATER_THAN
#define LESS_OR_EQUAL_THAN
#define GREATER_OR_EQUAL_THAN
#define DIFFERENT
#define ASSIGNMENT
#define EQUAL
#define POWER
#define OR
#define AND
#define NOT